version: '3'

http:
  address: 127.0.0.1:8000
  pool:
    debug: false
    num_workers: 4
    max_jobs: 250
    allocate_timeout: 60s
    destroy_timeout: 60s
    supervisor:
      exec_ttl: 30s
  static:
    dir: public
  middleware:
    - static
server:
  command: "php artisan octane:start --server=roadrunner --host=127.0.0.1 --port=8000"
  relay: pipes
rpc:
  listen: tcp://127.0.0.1:6001
logs:
  mode: production
  level: debug
  encoding: json
